# Generated by Django 4.0.3 on 2022-03-08 18:35

from django.db import migrations
import genres as genre_data


def create_genres(apps, schema_editor):
    Genre = apps.get_model("music", "Genre")
    for genre_name in genre_data.genres:
        Genre.objects.create(name=genre_name)


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_genre"),
    ]

    operations = [migrations.RunPython(create_genres)]
