# Generated by Django 4.0.3 on 2022-03-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20220308_1835'),
    ]

    operations = [
    ]
