# Generated by Django 4.0.3 on 2022-03-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20220308_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='music.genre'),
        ),
    ]
