# Generated by Django 4.0.3 on 2022-03-08 22:01

from django.db import migrations
from django.utils.text import slugify
from django.db.models import F


def create_slugs(apps, schema_editor):
    Genre = apps.get_model("music", "Genre")
    genres = Genre.objects.all()
    for genre in genres:
        genre.slug = slugify(genre.name)
        genre.save()


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0007_alter_album_genres"),
    ]

    operations = [
        migrations.RunPython(create_slugs),
    ]
