# Generated by Django 4.0.3 on 2022-03-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20220308_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, unique=True),
        ),
    ]
