# Generated by Django 4.0.3 on 2022-03-09 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0009_alter_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
